keys:
  - &yubikey age1yubikey1qgyrtg6drd9uzn7t8eqc3h08r6ck647ega4geq84escczjhuteqxv682jtn
  - &mac age1jt3ka82kdczm66ma3p6y65fuvxeky4vmeqarctl7el7rf7j20yfqavpkrf
creation_rules:
  - path_regex: .*\.sops\.[^/]+$
    key_groups:
      - age:
          - *yubikey
          - *mac
